# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BlazeBlock": "00_layers.ipynb",
         "BlazeFaceBlock": "00_layers.ipynb",
         "BlazePoseBlock": "00_layers.ipynb"}

modules = ["layers.py"]

doc_url = "https://vikramkalabi.github.io/blaze/"

git_url = "https://github.com/vikramkalabi/blaze/tree/master/"

def custom_doc_links(name): return None
